### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by greenstack** [greenstack/cc2#6]
To make the game more immersive, there should be some amount of animations implemented.

**Comment by frigid-dev** [comment]
I have the players animations in game. 
I have started rebuilding the animations for the npcs but can't hook them up until their movement is fixed.

**Comment by frigid-dev** [comment]
NPCs and companion are hooked up but there are a few tweaks needed still. Their sprites are getting tinted by one of the shaders for some reason so I am looking into that. 

I also need to build the rest of the animations so codewise I just need to add to the generator that will pick a matching icon and animation.

**Comment by frigid-dev** [comment]
There is always room to expand of course but I guess I will mark this done for now.
